-- MySQL Script generated by MySQL Workbench
-- 01/21/16 00:53:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qre
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `qre` ;

-- -----------------------------------------------------
-- Schema qre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qre` DEFAULT CHARACTER SET utf8 ;
USE `qre` ;

-- -----------------------------------------------------
-- Table `qre`.`classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`classe` ;

CREATE TABLE IF NOT EXISTS `qre`.`classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`groupe` ;

CREATE TABLE IF NOT EXISTS `qre`.`groupe` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(255) NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `classe_id`),
  CONSTRAINT `fk_Groupe_Classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `qre`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`etudiant` ;

CREATE TABLE IF NOT EXISTS `qre`.`etudiant` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `date_naiss` DATE NULL,
  `num_etu` VARCHAR(255) NULL,
  `groupe_id` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `groupe_id`, `classe_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `num_etu_UNIQUE` (`num_etu` ASC),
  CONSTRAINT `fk_Etudiant_Groupe1`
    FOREIGN KEY (`groupe_id` , `classe_id`)
    REFERENCES `qre`.`groupe` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`matiere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`matiere` ;

CREATE TABLE IF NOT EXISTS `qre`.`matiere` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`professeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`professeur` ;

CREATE TABLE IF NOT EXISTS `qre`.`professeur` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`emargement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`emargement` ;

CREATE TABLE IF NOT EXISTS `qre`.`emargement` (
  `id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `url_generated` VARCHAR(255) NOT NULL,
  `type` ENUM('CM', 'TD', 'TP') NULL,
  `matiere_id` INT NOT NULL,
  `professeur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `matiere_id`, `professeur_id`),
  CONSTRAINT `fk_Emargement_Matiere1`
    FOREIGN KEY (`matiere_id`)
    REFERENCES `qre`.`matiere` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emargement_Professeur1`
    FOREIGN KEY (`professeur_id`)
    REFERENCES `qre`.`professeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`signature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`signature` ;

CREATE TABLE IF NOT EXISTS `qre`.`signature` (
  `emargement_id` INT NOT NULL,
  `etudiant_id` INT NOT NULL,
  `signee` TINYINT(1) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`emargement_id`, `etudiant_id`),
  CONSTRAINT `fk_Emargement_has_Etudiant_Emargement1`
    FOREIGN KEY (`emargement_id`)
    REFERENCES `qre`.`emargement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emargement_has_Etudiant_Etudiant1`
    FOREIGN KEY (`etudiant_id`)
    REFERENCES `qre`.`etudiant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`groupe_has_emargement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`groupe_has_emargement` ;

CREATE TABLE IF NOT EXISTS `qre`.`groupe_has_emargement` (
  `groupe_id` INT NOT NULL,
  `classe_id` INT NOT NULL,
  `emargement_id` INT NOT NULL,
  `matiere_id` INT NOT NULL,
  `professeur_id` INT NOT NULL,
  PRIMARY KEY (`groupe_id`, `classe_id`, `emargement_id`, `matiere_id`, `professeur_id`),
  CONSTRAINT `fk_Groupe_has_Emargement_Groupe1`
    FOREIGN KEY (`groupe_id` , `classe_id`)
    REFERENCES `qre`.`groupe` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Groupe_has_Emargement_Emargement1`
    FOREIGN KEY (`emargement_id` , `matiere_id` , `professeur_id`)
    REFERENCES `qre`.`emargement` (`id` , `matiere_id` , `professeur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`professeur_has_classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`professeur_has_classe` ;

CREATE TABLE IF NOT EXISTS `qre`.`professeur_has_classe` (
  `professeur_id` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`professeur_id`, `classe_id`),
  CONSTRAINT `fk_Professeur_has_Classe_Professeur1`
    FOREIGN KEY (`professeur_id`)
    REFERENCES `qre`.`professeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professeur_has_Classe_Classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `qre`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`authentication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`authentication` ;

CREATE TABLE IF NOT EXISTS `qre`.`authentication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NULL,
  `date_expiration` DATETIME NULL,
  `professeur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professeur_id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  CONSTRAINT `fk_authentication_professeur1`
    FOREIGN KEY (`professeur_id`)
    REFERENCES `qre`.`professeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
