-- MySQL Script generated by MySQL Workbench
-- 01/19/16 01:42:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qre
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `qre` ;

-- -----------------------------------------------------
-- Schema qre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qre` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `qre` ;

-- -----------------------------------------------------
-- Table `qre`.`classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`classe` ;

CREATE TABLE IF NOT EXISTS `qre`.`classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`groupe` ;

CREATE TABLE IF NOT EXISTS `qre`.`groupe` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `classe_id`),
  CONSTRAINT `fk_groupe_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `qre`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`etudiant` ;

CREATE TABLE IF NOT EXISTS `qre`.`etudiant` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `date_naiss` DATE NULL,
  `num_etu` VARCHAR(45) NULL,
  `groupe_id` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`id`, `groupe_id`, `classe_id`),
  CONSTRAINT `fk_etudiant_groupe1`
    FOREIGN KEY (`groupe_id` , `classe_id`)
    REFERENCES `qre`.`groupe` (`id` , `classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`matiere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`matiere` ;

CREATE TABLE IF NOT EXISTS `qre`.`matiere` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`professeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`professeur` ;

CREATE TABLE IF NOT EXISTS `qre`.`professeur` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`emargement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`emargement` ;

CREATE TABLE IF NOT EXISTS `qre`.`emargement` (
  `id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `url_generated` VARCHAR(255) NOT NULL,
  `type` ENUM('CM', 'TD', 'TP') NULL,
  `matiere_id` INT NOT NULL,
  `professeur_id` INT NOT NULL,
  PRIMARY KEY (`id`, `matiere_id`, `professeur_id`),
  CONSTRAINT `fk_emargement_matiere1`
    FOREIGN KEY (`matiere_id`)
    REFERENCES `qre`.`matiere` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emargement_professeur1`
    FOREIGN KEY (`professeur_id`)
    REFERENCES `qre`.`professeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`signature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`signature` ;

CREATE TABLE IF NOT EXISTS `qre`.`signature` (
  `emargement_id` INT NOT NULL,
  `etudiant_id` INT NOT NULL,
  `signee` TINYINT(1) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`emargement_id`, `etudiant_id`),
  CONSTRAINT `fk_emargement_has_etudiant_emargement1`
    FOREIGN KEY (`emargement_id`)
    REFERENCES `qre`.`emargement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emargement_has_etudiant_etudiant1`
    FOREIGN KEY (`etudiant_id`)
    REFERENCES `qre`.`etudiant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qre`.`emargement_has_classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qre`.`emargement_has_classe` ;

CREATE TABLE IF NOT EXISTS `qre`.`emargement_has_classe` (
  `emargement_id` INT NOT NULL,
  `matiere_id` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`emargement_id`, `matiere_id`, `classe_id`),
  CONSTRAINT `fk_emargement_has_classe_emargement1`
    FOREIGN KEY (`emargement_id` , `matiere_id`)
    REFERENCES `qre`.`emargement` (`id` , `matiere_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emargement_has_classe_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `qre`.`classe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
